name: Deploy Cloud Functions
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: gcf_actions_template
          runtime: python39
          credentials: ${{ secrets.gcp_credentials }}
          entry_point: hello_pubsub
          region: asia-northeast1
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.gcp_project_id }}/topics/my-pubsub-topic
          env_vars: DISCORD_WEBHOOK_URL=${{ secrets.discord }}
